FROM node:16.19.1-alpine3.17

WORKDIR /frontend

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install --force

COPY . .

CMD [ "npm", "run", "dev", "--", "--host=0.0.0.0" ]